del .\Bin\ConnectServer\Logs /q
del .\Bin\DataServer1\Logs /q
del .\Bin\DataServer2\Logs /q
del .\Bin\ExDB\Logs /q
del .\Bin\JoinServer\Logs\SQLError /q
del .\Bin\JoinServer\Logs /q
del .\Bin\ChatServer\LOG /q
del .\GameServer\Logs\BotLog /q
del .\GameServer\Logs\ChaosBox /q
del .\GameServer\Logs\ChatLogs /q
del .\GameServer\Logs\Commands /q
del .\GameServer\Logs\Server /q
del .\GameServer\Logs\TradeLogs /q
del .\GameServer\Logs\XS /q
del .\GameServerCS\Logs\BotLog /q
del .\GameServerCS\Logs\ChaosBox /q
del .\GameServerCS\Logs\ChatLogs /q
del .\GameServerCS\Logs\Commands /q
del .\GameServerCS\Logs\Server /q
del .\GameServerCS\Logs\TradeLogs /q
del .\GameServerCS\Logs\XS /q
del .\GameServerCS\Logs\Events /q